const BESOIN_MODELE = [
  { idee:'Lecture des pièces justificatives reçues (OCR puis extraction des champs)',
    apport:'transforme un PDF ou un scan en champs exploitables : numéro, date, montant, quantité',
    verif:'≈ 1 à 2 min par pièce : chaque champ qui entre au dossier est relu sur la pièce d’origine' },
  { idee:'Pointage de la plaquette client contre la balance auditée',
    apport:'lit les états financiers publiés et les rapproche poste à poste des montants audités',
    verif:'≈ 20 à 40 min par plaquette : le rapprochement est relu ligne à ligne, chaque écart tranché' },
  { idee:'Vidéo/transcript d’entretien de contrôle interne, documentation de la compréhension',
    apport:'restitue le déroulé décrit et en tire une première description du processus',
    verif:'≈ 30 à 60 min par entretien : la description devient une diligence, elle est réécrite et validée' },
  { idee:'Comparaison du discours client au flowchart fourni',
    apport:'signale les points où ce qui est dit ne correspond pas au schéma remis',
    verif:'≈ 15 à 30 min : chaque incohérence signalée est confirmée avant d’être opposée au client' },
  { idee:'Analyse macroéconomique et facteurs externes',
    apport:'rassemble et résume un contexte sectoriel dispersé',
    verif:'≈ 30 min : rien n’entre au dossier sans source vérifiée ; c’est un support de réflexion, pas un élément probant' },
  { idee:'Détection de liens entre l’organigramme et les tiers (risque de fraude)',
    apport:'rapproche des noms et des entités entre deux listes hétérogènes',
    verif:'≈ 10 min par rapprochement proposé, et aucun ne devient une conclusion sans vérification externe' },
  { idee:'Proposition du couple référence/taux de matérialité, avec sa justification',
    apport:'propose et rédige la motivation à partir des caractéristiques de l’entité',
    verif:'≈ 10 min : la proposition n’a aucune valeur tant qu’un humain ne l’a pas arrêtée' },
];
const FAUSSEMENT_AGENT = [
  { idee:'« un agent IA pré-remplit des tests qui vont faire ressortir des écritures »',
    reel:'Test des écritures (module 5) — ce sont des prédicats : week-end, montant rond, journal, date de validation, auteur de la saisie.' },
  { idee:'« un scoping automatique des FSLIs selon la matérialité »',
    reel:'Scoping (module 3) — une comparaison de solde à un seuil.' },
  { idee:'« Revue analytique générée automatiquement […] des questions […] automatiquement envoyée au client »',
    reel:'Revue analytique (module 4) — soustraction, division, et une phrase assemblée à partir de champs.' },
  { idee:'« un agent IA regarde la comptabilité et vérifie qu’il ne manque pas de banque »',
    reel:'Exhaustivité des circularisations (module 7) — une différence entre deux ensembles.' },
  { idee:'« font la réconciliation de ce compte à notre solde en TB »',
    reel:'Rapprochement (module 1) — une somme par compte et une comparaison.' },
  { idee:'« l’agent IA devra aussi relancer le client pour les demandes non-remplies »',
    reel:'Suivi des demandes (module 8) — une comparaison de date d’échéance.' },
  { idee:'« Un chat bot général qui répond aux questions de l’associé »',
    reel:'Ce qui est utile ici n’est pas la conversation mais la requête : une question type se traduit en filtre sur les données et rend des enregistrements, pas de la prose.' },
];